### ISSUE TITLE
No module named OpenEXR

### ISSUE THREAD

**Issue by poisonwine** [wyysf-98/shapenet_render#1]
hello ,when I run the 'python run.py' ,it gives error "ModuleNotFoundError: No module named 'OpenEXR'"
But I include my conda virtual env,and the env has OpenEXR. Should I install OpenEXR in blender python?

**Comment by wyysf-98** [comment]
Hello, if you have OpenEXR already, just change the include_path in config.py is OK.

**Comment by poisonwine** [comment]
OK ,it has been solved. But the results seem strange:

Blender 2.83.5 (hash c2b144df395f built 2020-08-19 06:05:02)
found bundled python: /home/ydy/blender-2.83.5-linux64/2.83/python
Info: Deleted 1 object(s)
Info: Deleted 1 object(s)

Blender quit

**Comment by wyysf-98** [comment]
Please check the data path. The info means deleting the origin cube in blender.

**Comment by poisonwine** [comment]
Ok, thanks , I fixed it. But I am still a little confused about a ShapeNet model.
The model category is 'table',and path is 04379243/f44c91626e4900a5a26aea0642029fc,  it  actually has texture file,but 
when using blender to get its rbg image(https://github.com/poisonwine/hw5/blob/master/2.png), it seems has no texture 
. I don't know why this happen

**Comment by wyysf-98** [comment]
Acatually I'm not sure. I guess it’s may because of the conversation of .glb format. Some triangles in shapenet model may not correct, please see the link in ReadMe. So if most of the models are correct, you can ignore it.

**Comment by poisonwine** [comment]
Actually, I have already save the .glb in the .obj path, but .glb and .obj get the same rgb image.
I don't konw how many objects have the same problem

**Comment by wyysf-98** [comment]
You can use the official version of shapenet render to check the result. I only use part of the shapenet data, and this problem doesn't affect the result.

**Comment by poisonwine** [comment]
Ok I will try it tomorrow.Thanks a lot!
